spring:
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32055/bssm_secret_shop
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update