spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bssm_secret_shop
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect